application:
  login: ${app_login}
  password: ${app_password}
vk:
  link: ${vk_link}
  group: ${vk_group}
  client: ${vk_client}
  secret: ${vk_secret}
  token: ${vk_token}

website:
  domain: odnodolshiki2.ru
  url: https://odnodolshiki2.ru
  username: ${website_user_name}
  password: ${website_user_pass}

spring:
  datasource:
    url: ${spring_datasource_url}
    username: ${spring_datasource_username}
    password: ${spring_datasource_password}
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${spring_jpa_hibernate_ddl_auto}
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: ${spring_jpa_database_platform}