vk:
  group: -1
  client: 1
  secret: secret
  service: service
website:
  domain: odnodolshiki2.ru
  url: https://odnodolshiki2.ru
  username: <user>
  password: <pass>

spring:
  datasource:
    url: <url>
    username: <username>
    password: <password>
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect